### ISSUE TITLE
hbond

### ISSUE THREAD

**Issue by ruska612** [MDplot/MDplot#1]

**Comment by ruska612** [comment]
Hi, for hbond analysis using GROMACS engine, a log file from gromacs hbond command must be needed. However, when I used "gmx_mpi hbond -g hbond.log", no log file could be generated and my gromacs is 5.1 version.

**Comment by percuisses** [comment]
Thanks for your feedback!

> Hi, for hbond analysis using GROMACS engine, a log file from gromacs hbond command must be needed. However, when I used "gmx_mpi hbond -g hbond.log", no log file could be generated and my gromacs is 5.1 version.

That is strange, though. I tried the "-g" option in both GROMACS 2016 and 2018 and it still seems to be supported. Could you post the whole invocation?
