### ISSUE TITLE
How to load gromacs tpr (trajectory) file into the MDplot 

### ISSUE THREAD

**Issue by natarajmtech** [MDplot/MDplot#2]
Dear Developer,
I would like plot graph of dssp analysis of my 20ns MD trajectory using Gromacs , I am not sure how to load the trajectory file in tpr format produced by groamcs into the MDplot.
Regards,
Nataraj

**Comment by CMargreitter** [comment]
Hej,
MDplot has no trajectory parser of its own, you will need to generate e.g. RMSD data using the MD engine's tools (for GROMACS I believe it is "gmx rms"). Have a look at the example files here: https://github.com/MDplot/MDplot/tree/master/MDplot/inst/extdata

**Comment by natarajmtech** [comment]
Thank you very much for your reply and it helpful for my work.
Regards,
Nataraj
